//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homematic.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homematic.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; ?&gt;
        ///&lt;deviceList&gt;
        ///  &lt;device name=&apos;Allgemein Wohnbereich / Küche&apos; address=&apos;MEQ1004981&apos; ise_id=&apos;1349&apos; interface=&apos;BidCos-RF&apos; device_type=&apos;HM-LC-Sw4-DR&apos; ready_config=&apos;true&apos;&gt;
        ///    &lt;channel name=&apos;HM-LC-Sw4-DR MEQ1004981:1&apos; type=&apos;26&apos; address=&apos;MEQ1004981:1&apos; ise_id=&apos;1374&apos; direction=&apos;RECEIVER&apos; parent_device=&apos;1349&apos; index=&apos;1&apos; group_partner=&apos;&apos; aes_available=&apos;true&apos; transmission_mode=&apos;DEFAULT&apos; visible=&apos;true&apos; ready_config=&apos;true&apos; operate=&apos;true&apos; /&gt;
        ///    &lt;channel name=&apos;HM-LC-Sw4-DR ME [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Devicelist {
            get {
                return ResourceManager.GetString("Devicelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; ?&gt;
        ///&lt;state&gt;
        ///  &lt;device name=&apos;Thermostat - Bad&apos; ise_id=&apos;2074&apos; unreach=&apos;false&apos; sticky_unreach=&apos;true&apos; config_pending=&apos;false&apos; &gt;
        ///    &lt;channel name=&apos;Thermostat - Bad:0&apos; ise_id=&apos;2075&apos;&gt;
        ///      &lt;datapoint name=&apos;BidCos-RF.MEQ0863092:0.UNREACH&apos; type=&apos;UNREACH&apos; ise_id=&apos;2096&apos; value=&apos;false&apos; valuetype=&apos;2&apos; valueunit=&apos;&apos; timestamp=&apos;1559396782&apos; /&gt;
        ///      &lt;datapoint name=&apos;BidCos-RF.MEQ0863092:0.STICKY_UNREACH&apos; type=&apos;STICKY_UNREACH&apos; ise_id=&apos;2092&apos; value=&apos;true&apos; valuetype=&apos;2&apos; valueunit=&apos;&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeviceState2074 {
            get {
                return ResourceManager.GetString("DeviceState2074", resourceCulture);
            }
        }
    }
}
